### PR TITLE
Add simple configuration menu to the mod

### PR DESCRIPTION
**Pull request by FrozenAlex**
This is not very optimal since the modal gets recreated on every click on the "settings" button, but now it has settings!
It supports all of the endpoints of waifu.pics, except it does not support gifs.

### CODE REVIEW

**Comment by Futuremappermydud** [comment]
I ask for now that nsfw is taken out of the config, it can be in the code as a hard coded toggle but I don’t know how nsfw should be handled atm

**Comment by FrozenAlex** [comment]
I added a compiler flag for nsfw content and added it to CMakeLists.txt disabled by default

**Comment by FrozenAlex** [comment]
The original mod actually has a toggle for nsfw as well, they just ask you twice before enabling it.

**Comment by Futuremappermydud** [comment]
> The original mod actually has a toggle for nsfw as well, they just ask you twice before enabling it.

I know it has a toggle just ya know most pc players are older than quest players

**Comment by FrozenAlex** [comment]
Fair point xD

**Pull request merged**
